# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50401385e86d55eb282844d1434d1005b1ebfafdabcc26c10388e3aca34d390e88f3b5838a8f633a8426fe15292c989fd8b61c71cf430e18b476a37aa4de0874

test:
  secret_key_base: 5a0e5dbdeb780e743c9212e1e8e115f72c0edc435361657f2d2092fff43b9d5bf653f8830c291cb1462b19d23cc09cd832c5f6caae1ac2ca1ad317855aaf46ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
